platform :ios, "7.0"

pod "AFNetworking"
pod 'Mantle'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ImagePlayerView'
pod 'VKVideoPlayer', '~> 0.1.1'
pod "Mantle-HAL"


target :MyDotaTests, :exclusive => true do
  # pod 'Kiwi'
end