platform :ios, "7.0"

target :MyDota do

pod 'AFNetworking','~> 2.6.3'
pod 'Mantle'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ImagePlayerView'
pod 'VKVideoPlayer', '~> 0.1.1'
pod 'Mantle-HAL'
pod 'UMengAnalytics'
pod 'UzysAssetsPickerController'
pod 'UMengFeedback'
pod 'Masonry', '0.6.1' #autolayout解析
pod 'JSPatchPlatform'


end
